# Build widevinecdm.dll from the nimony sources + C++ shim + mbedTLS.
#
#   tools\build.ps1 [-Wvd <path-to-.wvd>] [-NimonyExe <path>]
#
# Steps: bake the device identity into src/embedded_device.nim, compile the
# project with nimony --app:lib, and copy the result to dist/widevinecdm.dll.
# Run mbedTLS's build first (tools/fetch-mbedtls.ps1) so libmbedcrypto.a exists.
param(
  [string]$Wvd = "",
  [string]$NimonyExe = "$env:USERPROFILE\nimony\bin\nimony.exe"
)
$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$src = Join-Path $root "src"
$mbed = Join-Path $root "third-party\mbedtls\library\libmbedcrypto.a"

if (-not (Test-Path $mbed)) {
  Write-Warning "libmbedcrypto.a not found at $mbed — run tools\fetch-mbedtls.ps1 first."
}

# --- bake the device identity ---------------------------------------------
if ($Wvd -eq "") { $Wvd = Join-Path $root "embedded.wvd" }
$embedNim = Join-Path $src "embedded_device.nim"
# Bootstrap the (gitignored) working copy from the committed stub if absent.
if (-not (Test-Path $embedNim)) {
  Copy-Item (Join-Path $src "embedded_device.nim.example") $embedNim
}
if (Test-Path $Wvd) {
  Write-Host "Embedding device identity from $Wvd"
  $bytes = [System.IO.File]::ReadAllBytes($Wvd)
  $sb = New-Object System.Text.StringBuilder
  [void]$sb.AppendLine('## Auto-generated by tools/build.ps1 from the embedded .wvd. Do not commit.')
  [void]$sb.AppendLine('const deviceArr = [')
  $line = "  byte "          # `byte` prefix on the first element types the array
  $first = $true
  foreach ($b in $bytes) {
    if ($first) { $line += ([string]$b); $first = $false }
    else { $line += (", " + [string]$b) }
    if ($line.Length -gt 90) { [void]$sb.AppendLine($line); $line = "  " }
  }
  if ($line.Trim().Length -gt 0) { [void]$sb.AppendLine($line) }
  [void]$sb.AppendLine(']')
  [void]$sb.AppendLine('')
  [void]$sb.AppendLine('proc embeddedDevice*(): seq[byte] =')
  [void]$sb.AppendLine('  result = @[]')
  [void]$sb.AppendLine('  for b in deviceArr:')
  [void]$sb.AppendLine('    result.add b')
  [System.IO.File]::WriteAllText($embedNim, $sb.ToString())
} else {
  Write-Warning "No .wvd at $Wvd — building with an EMPTY device (license requests will fail)."
}

# --- compile ---------------------------------------------------------------
Push-Location $src
try {
  $buildDir = Join-Path $root "build"
  & $NimonyExe c --app:lib --nimcache:$buildDir -f widevine.nim
  if ($LASTEXITCODE -ne 0) { throw "nimony build failed (exit $LASTEXITCODE)" }
} finally { Pop-Location }

# --- collect output --------------------------------------------------------
$dll = Get-ChildItem (Join-Path $root "build") -Recurse -Filter widevine.dll |
       Sort-Object LastWriteTime | Select-Object -Last 1
if (-not $dll) { throw "widevine.dll not produced" }
$dist = Join-Path $root "dist"
New-Item -ItemType Directory -Force -Path $dist | Out-Null
Copy-Item $dll.FullName (Join-Path $dist "widevinecdm.dll") -Force
Write-Host "Built dist\widevinecdm.dll ($([math]::Round($dll.Length/1kb)) KB)"
